spring:
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"
  shell:
    interactive:
      enabled: true

localization:
  locale: ru

quiz:
  idx:
    abcdefghijklmnopqrstuvwxyz
  score: 3
